### ISSUE TITLE
localbase data populating drop-down menu

### ISSUE THREAD

**Issue by CynthiaBlue** [dannyconnell/localbase#13]
I like locabase and have incorporated it into my project.

I need to populate a drop-down menu in Quasar with a list of items retrieved from the indexedDB/localbase database and I'm not sure of the syntax.

This is my q-select:
```
        <q-select
          filled
          v-model="theOwner"
          bg-color="grey-3"
          :options="options"
          label="Owner"
          hint="Owner - must exist as a person" /> 
```

But I'm not sure how to format the 'options' in the data return.  I would love help, thanks.

**Comment by dannyconnell** [comment]
@CynthiaBlue this is not a Localbase issue. The Quasar site will tell you what format the options object should be in. You just need some logic to convert the array accordingly. Please only post Localbase issues or feature requests here.
