### ISSUE TITLE
Set throws error with array

### ISSUE THREAD

**Issue by CynthiaBlue** [dannyconnell/localbase#17]
In your description you have this to update an entire collection:

db.collection('users')
  .set([
    {
      id: 1,
      name: 'Bill',
      age: 48
    },
    {
      id: 2, 
      name: 'Paul',
      age: 28
    }
  ])

//  [
//    { id: 1, name: 'Bill', age: 48 },
//    { id: 2, name: 'Paul', age: 28 }
//  ]

But when I use that syntax, I am getting an error.  This is my syntax:
      db.collection('tableHoldPeopleID')
      .set([
        {
          id: "hi there",
          anotherfield: 'another field'
        }
      ])

And this is the error:
"localbase Data passed to .set() must be an object. Not an array, string, number or boolean."

**Comment by dannyconnell** [comment]
@CynthiaBlue do you have the latest version (0.7.4)? This capability was only added in the latest version.
