### ISSUE TITLE
Could not add Document to [collectionName] collection.

### ISSUE THREAD

**Issue by GuyTito** [dannyconnell/localbase#29]
not able to add a document to collection
this is the document: 
{"bag_id":"2021-03-10T18:09:35.892Z","bag_name":"items for party","comment":"","currency":"₵","items":[]}

![could not add](https://user-images.githubusercontent.com/35842294/110678210-f4c8a100-81cd-11eb-9a69-3d415f074626.PNG)

**Comment by moha5145** [comment]
Are you using Localbase with vue.js 3 composition-Api?

**Comment by GuyTito** [comment]
I'm not using composition API. I came across a solution by using JSON.parse(JSON.stringify({object})) inside the Localbase methods.

**Comment by tobiornottobi** [comment]
@GuyTito Can you explain the solution again?
I am getting the error at this point of the tutorial https://youtu.be/KJnupY2HPCg?t=522
