### ISSUE TITLE
Not able to get this functioning in a Nuxt JS project

### ISSUE THREAD

**Issue by lcharleslaing** [dannyconnell/localbase#3]
I've tried many strategies and all have comeback with the same error.  I was able to create within a Quasar app per the video tutorial but not in Nuxt JS as of yet.

I installed via **yarn add localbase** and it installed **"localbase": "^0.7.4"**
Also, to be sure, I installed it again via **npm install localbase --save**

SyntaxError
**Cannot use import statement outside a module**

the error also includes **Missing stack frame**

Ive tried the following...

- Importing and creating the db on the component/page level and added the **import** and **let db** lines with the script tag before the export default.
- Creating a plugin (no errors until I added the **import** and **let db** lines to the file)
- Creating a module (no errors until I added the **import** and **let db** lines to the file)

![screencapture-localhost-64236-2020-09-30-11_28_34](https://user-images.githubusercontent.com/71520336/94706542-4fe99400-0310-11eb-9318-db8526e8818f.png)

**Comment by AlexanderM1927** [comment]
I got same problem, did u solutioned?

**Comment by dannyconnell** [comment]
@lcharleslaing @AlexanderM1927 you need to create a plugin. This worked for me (I'll add this to the localbase readme):

#### With NuxtJS

```javascript
// plugins/localbase.js

import Localbase from 'localbase'
let db = new Localbase('db')
export default (context,inject) => {
  inject('db', db)
}
```

```javascript
// nuxt.config.js

export default {
  ...
  plugins: [
    { src: "~/plugins/localbase", mode: "client" }
  ],
  ...
}
```

```html
<!-- pages/index.vue -->

<script>
export default {
  head: {
    title: 'Nuxt Blog - Home'
  },
  mounted() {
    this.$db.collection('users').add({
      id: 1,
      name: 'Bill',
      age: 47
    })
  }
}
</script>
```
