### ISSUE TITLE
localbase fails to add records on Opera

### ISSUE THREAD

**Issue by dantrevino** [dannyconnell/localbase#5]
To be up front, I'm not sure if this is really an Opera issue, but thought I'd raise it here, even if just for awareness.

`db.collection("foo").add(bar)` fails in add.js line 19.

I do *not* see the same behavior in current versions of chrome or chromium.

version info:
Version:72.0.3815.148
Opera is up to date
Update stream:Stable
System:Ubuntu 20.04.1 LTS (x86_64; ubuntu:GNOME)

**Comment by dannyconnell** [comment]
Hi Dan,

Could you please paste the object you are trying to add to the collection?

I'm wondering if this only happens under certain conditions regarding the object.

Cheers,

Danny

**Comment by dantrevino** [comment]
Sorry, user error.  Ad block is on by default.  Disabling that made everything work fine.  Apologies.
