### ISSUE TITLE
get function returning object instead of array.

### ISSUE THREAD

**Issue by daniel329paul** [dannyconnell/localbase#61]
get function is returning first document in the collection instead of fetching all the documents.
query:-
`db.collection("app_bar").get()`

output:-
`{
    "bot_name": "Tomato",
    "bot_icon": "data:image/png;base64,iVBOR",
    "bot_type": "External"
}`

Kindly help, what is the reason for this to happen. im using my own custom keys. keys are string.

 `db.collection('app_bar').doc(e.bot_name).set(e);`

**Comment by Sandro48** [comment]
I have the exact same problem.
When fetching multiple times, it's fetching the collection correctly most of the times, only sometimes it returns the first document of the collection.

**Comment by danny329** [comment]
I was facing this issue when using async/await to handle promises on local base. But when I started using .then() i didn't get those issues.

**Comment by HEAVYPOLY** [comment]
Same happening here.  using await.
