### ISSUE TITLE
Set a collection (overwrite) - problem

### ISSUE THREAD

**Issue by strublos** [dannyconnell/localbase#8]
Hi, when I use example from readme
```
db.collection('users')
  .set([
    {
      id: 1,
      name: 'Bill',
      age: 48
    },
    {
      id: 2, 
      name: 'Paul',
      age: 28
    }
  ])
```
I got error
` Data passed to .set() must be an object. Not an array, string, number or boolean.`
It does not matter if the 'table' users exists or not

**Comment by CynthiaBlue** [comment]
I get this same error.  I am thinking I may change to using Dexie instead of localbase.

**Comment by dannyconnell** [comment]
@strublos do you have the latest version (0.7.4)? This capability was only added in the latest version.

**Comment by strublos** [comment]
download master today, (in package.json there is version 7.0.5)
but still same error

test index.html file
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TEST</title>
  <script src="./dist/localbase.dev.js"></script>
  <script>
  let db = new Localbase('dbmaster');
db.collection('users')
  .set([
    {
      id: 2,
      name: 'Bill',
      age: 48
    },
    {
      id: 3, 
      name: 'Paul',
      age: 28
    }
  ])
  </script>

</head>
<body>
</body>
</html>
```

**Comment by nevenpalcec** [comment]
> I have try to add a list / array of objects, but its not working...
An error:  Data passed to .set() must be an object. Not an array, string, number or boolean.
